// Basic widget test demonstrating that the application can be instantiated
// without throwing `ProviderNotFoundException`. The original counter example
// generated by `flutter create` was removed since the app has no such widget.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:get_it/get_it.dart';

import 'package:noize/main.dart';
import 'package:noize/core/providers/settings_provider.dart';
import 'package:noize/core/providers/queued_provider.dart';
import 'package:noize/core/providers/download_provider.dart';
import 'package:noize/core/providers/stats_provider.dart';
import 'package:noize/core/providers/favorite_song_provider.dart';
import 'package:noize/core/providers/player_provider.dart';
import 'package:noize/core/providers/video_info_provider.dart';

void main() {
  testWidgets('App builds with required providers', (
    WidgetTester tester,
  ) async {
    // create minimal provider instances and register video info provider in GetIt
    final settingsProvider = SettingsProvider();
    final queueProvider = QueueProvider();
    final downloadProvider = DownloadProvider();
    final statsProvider = StatsProvider();
    final favoriteSongProvider = FavoriteSongProvider();

    GetIt.I.registerSingleton<VideoInfoProvider>(VideoInfoProvider());

    await tester.pumpWidget(
      MultiProvider(
        providers: [
          ChangeNotifierProvider.value(value: settingsProvider),
          ChangeNotifierProvider.value(value: queueProvider),
          ChangeNotifierProvider.value(value: downloadProvider),
          ChangeNotifierProvider.value(value: statsProvider),
          ChangeNotifierProvider.value(value: favoriteSongProvider),
          ChangeNotifierProvider(
            create: (_) => PlayerProvider(
              queueProvider,
              downloadProvider,
              GetIt.I<VideoInfoProvider>(),
              statsProvider,
              favoriteSongProvider,
            ),
          ),
        ],
        child: const NoizeApp(),
      ),
    );

    // simply verify the root widget exists
    expect(find.byType(NoizeApp), findsOneWidget);
  });
}
