// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'features/home/data/providers/home_screen_provider.dart';
import 'features/trending/data/provider/trending_provider.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlbumDetailedDTOAdapter());
    registerAdapter(ArtistBasicDTOAdapter());
    registerAdapter(ArtistDTOAdapter());
    registerAdapter(ContentItemDTOAdapter());
    registerAdapter(HomeSectionDTOAdapter());
    registerAdapter(PlaylistDetailedDTOAdapter());
    registerAdapter(SongInfoDTOAdapter());
    registerAdapter(ThumbnailDTOAdapter());
    registerAdapter(ThumbnailFullDTOAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlbumDetailedDTOAdapter());
    registerAdapter(ArtistBasicDTOAdapter());
    registerAdapter(ArtistDTOAdapter());
    registerAdapter(ContentItemDTOAdapter());
    registerAdapter(HomeSectionDTOAdapter());
    registerAdapter(PlaylistDetailedDTOAdapter());
    registerAdapter(SongInfoDTOAdapter());
    registerAdapter(ThumbnailDTOAdapter());
    registerAdapter(ThumbnailFullDTOAdapter());
  }
}
